apiVersion: v1
kind: Service
metadata:
  name: inference-service
  labels:
    app: inference-worker
    research-project: inference-cluster
spec:
  type: ClusterIP  # For internal cluster access
  ports:
  - port: 80        # Service port
    targetPort: 8080 # Container port
    protocol: TCP
    name: http
  selector:
    app: inference-worker
  sessionAffinity: None
